# Generated by Django 3.0.5 on 2022-05-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scmapp', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
